version: '3.2'
services:
  api:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./api:/var/www/html:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fpm
    networks:
      - bean-sync-app

  fpm:
    build: ./docker/fpm
    volumes:
      - ./api:/var/www/html:cached
      - ./docker/fpm/php.ini:/usr/local/etc/php/php.ini
      - './api/messenger-worker.conf:/etc/supervisor/conf.d/messenger-worker.conf'
    networks:
      - bean-sync-app

  react-app:
    build: ./react-app
    environment:
      NPM_CONFIG_CACHE: /.npm
    volumes:
      - './react-app:/react-app:cached'
      - /react-app/node_modules
      - './react-app/.npm:/.npm'
    ports:
      - "3000:3000"
    command: npm run start
    networks:
      - bean-sync-app

  mongo:
    image: mongo:3.4.16-jessie
    volumes:
      - './docker/data/mongo/db:/data/db'
      - './docker/data/mongo/restore:/data/restore:ro'
    networks:
      - bean-sync-app

#  redis:
#    image: redis:3.2.1-alpine
#    volumes:
#      - './docker/compose/data/redis:/data'
#    networks:
#      - bean-sync-app

  rabbitmq:
    build:
      context: .
      dockerfile: docker/rabbitmq/Dockerfile
    volumes:
      - ./docker/data/rabbitmq:/var/lib/rabbitmq/mnesia:cached
    ports:
      - 15673:15673
    networks:
      - bean-sync-app

networks:
  bean-sync-app:
    driver: bridge
