framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            pipeline_processing:
                dsn: '%app.messenger.transport.dsn%'
                options:
                    exchange:
                        name: pipeline_processing
                    queues:
                        pipeline_processing: ~
                retry_strategy:
                    max_retries: 3
                    # milliseconds delay
                    delay: 1000
                    # causes the delay to be higher before each retry
                    # e.g. 1 second delay, 2 seconds, 4 seconds
                    multiplier: 2
                    max_delay: 0
                    # override all of this with a service that
                    # implements Symfony\Component\Messenger\Retry\RetryStrategyInterface
                    # service: null

            # https://symfony.com/doc/current/messenger.html#transport-configuration
            failed: '%app.messenger.transport.dsn%_failed'
            # sync: 'sync://'
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            # Route your messages to the transports
            'App\Message\Sync\Pipeline': pipeline_processing
